version: '3.7'
services:
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./proxy/:/etc/nginx/conf.d/:ro
    ports:
      - 0.0.0.0:80:80
    depends_on:
      - frontend
      - web-service


  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: &db_user ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: &db_pass ${MONGO_PASSWORD}

  rabbitmq:
    image: rabbitmq:3.7-alpine
    restart: unless-stopped

  frontend:
    restart: unless-stopped
    build:
      context: https://github.com/nebula-analytics/nebula.git
    environment:
      NODE_ENV: 'production'

  web-service:
    restart: unless-stopped
    build:
      context: https://github.com/nebula-analytics/nebula-webservice.git
      dockerfile: "Dockerfile"

    environment:
      WEB_CONCURRENCY: 2
      nebula_eve_MONGO_HOST: "mongo"
      nebula_eve_MONGO_USERNAME: *db_user
      nebula_eve_MONGO_PASSWORD: *db_pass
      nebula_eve_MONGO_AUTH_SOURCE: 'admin'
      nebula_eve_URL_PREFIX: ""
      LOG_LEVEL: "info"
    depends_on:
      - mongo

  setup-tool:
    restart: unless-stopped
    build:
      context: https://github.com/nebula-analytics/nebula-automated-setup.git
    environment:
      SECRET: ${SECRET}
      CONFIG_DIR: /config/nebula
    volumes:
      - type: volume
        source: config
        target: /config/nebula

    ports:
      - 127.0.0.1:5000:80

  node-1:
    restart: unless-stopped
    build:
      context: https://github.com/nebula-analytics/nebula-background-worker.git
    command:  "python -m celery -A schedule worker --loglevel=DEBUG -Q nebula.express,nebula.import -n node_1"
    environment: &worker_env
      "nebula.config.path": /config/config.yaml.docker
      nebula.database.mongodb.username: *db_user
      nebula.database.mongodb.password: *db_pass
      nebula.database.mongodb.host: "mongo"
      nebula.celery.broker_url:  "amqp://rabbitmq"
    depends_on: &worker_dep
      - mongo
      - rabbitmq
    volumes:
      - type: volume
        source: config
        target: /config
  node-2:
    restart: unless-stopped
    command:  "python -m celery -A schedule worker --loglevel=DEBUG -Q nebula.express -n node_1"
    build:
      context: https://github.com/nebula-analytics/nebula-background-worker.git
    depends_on:
      *worker_dep
    environment:
      *worker_env
    volumes:
      - type: volume
        source: config
        target: /config


  node-schedule:
    restart: unless-stopped
    build:
      context: https://github.com/nebula-analytics/nebula-background-worker.git
    command: "celery beat -A schedule --loglevel=DEBUG --pidfile="
    depends_on:
      - node-2

    environment:
      *worker_env

    volumes:
      - type: volume
        source: config
        target: /config
volumes:
  config: