version: '3.7'
services:
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./proxy/:/etc/nginx/conf.d/:ro
    ports:
      - 0.0.0.0:80:80
    depends_on:
      - frontend
      - web-service


  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: &db_user ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: &db_pass ${MONGO_PASSWORD}

  rabbitmq:
    image: rabbitmq:3.7-alpine
    restart: unless-stopped

  frontend:
    restart: unless-stopped
    build:
      context: "frontend"
    environment:
      NODE_ENV: 'production'
      REACT_APP_API_LOCATION: "/api"

  web-service:
    restart: unless-stopped
    build:
      context: "web"
      dockerfile: "Dockerfile"
    environment:
      WEB_CONCURRENCY: 2
      nebula_eve_MONGO_HOST: "mongo"
      nebula_eve_MONGO_USERNAME: *db_user
      nebula_eve_MONGO_PASSWORD: *db_pass
      nebula_eve_MONGO_AUTH_SOURCE: 'admin'
      nebula_eve_URL_PREFIX: ""
      LOG_LEVEL: "debug"
    depends_on:
      - mongo


  node-1:
    restart: unless-stopped
    build:
      context: "worker"
    command:  "python -m celery -A schedule worker --loglevel=DEBUG -Q nebula.express,nebula.import -n node_1"
    environment: &worker_env
      nebula.database.mongodb.username: *db_user
      nebula.database.mongodb.password: *db_pass
      nebula.database.mongodb.host: "mongo:27017"
      nebula.celery.broker_url:  "amqp://rabbitmq"
    depends_on: &worker_dep
      - mongo
      - rabbitmq

  node-2:
    restart: unless-stopped
    command:  "python -m celery -A schedule worker --loglevel=DEBUG -Q nebula.express -n node_1"
    build:
      context: "worker"
      dockerfile: "Dockerfile"
    depends_on:
      *worker_dep
    environment:
      *worker_env

  node-schedule:
    restart: unless-stopped
    build:
      context: "worker"
    command: "celery beat -A schedule --loglevel=DEBUG --pidfile="
    depends_on:
      - node-2

    environment:
      *worker_env