version: '3.7'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: &db_user root
      MONGO_INITDB_ROOT_PASSWORD: &db_pass example

  message_queue:
    image: rabbitmq:3.7-alpine
    restart: always
    ports:
      - 6379:6379
  frontend:
    build:
      context: "frontend"
    depends_on:
      - web_service
    ports:
      - "0.0.0.0:80:80"

  web_service:
    build:
      context: "web"
      dockerfile: "Dockerfile-dev"
    environment:
      nebula.eve.MONGO_URI: "mongodb://root:example@mongo:27017"
      #      nebula.eve.MONGO_HOST: "mongo"
      #      nebula.eve.MONGO_USERNAME: *db_user
      #      nebula.eve.MONGO_PASSWORD: *db_pass
      ##      nebula.eve.MONGO_AUTH_SOURCE: 'admin'
    restart: "always"
    depends_on:
      - mongo
    ports:
      - "0.0.0.0:8080:5000"

  node_1:

    build:
      context: "worker"
    command:  "python -m celery -A schedule worker --loglevel=DEBUG -Q nebula.express,nebula.import -n node_1"
    environment: &worker_env
      nebula.database.mongodb.username: *db_user
      nebula.database.mongodb.password: *db_pass
      nebula.database.mongodb.host: "mongo:27017"
      nebula.celery.broker_url:  "amqp://message_queue"
    depends_on: &worker_dep
      - mongo
      - message_queue
    restart: "always"

  node_2:
    command:  "python -m celery -A schedule worker --loglevel=DEBUG -Q nebula.express -n node_1"
    build:
      context: "worker"
      dockerfile: "Dockerfile"
    restart: "always"
    depends_on:
      *worker_dep
    environment:
      *worker_env
  node_scheduler:
    restart: "always"
    build:
      context: "worker"
    command: "celery beat -A schedule --loglevel=DEBUG --pidfile="
    depends_on:
      - mongo
      - message_queue

    environment:
      *worker_env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
